FROM python:3
COPY ./ ./app/
RUN pip install -r requirements.txt && \
	apt-get update && \
	apt-get -y install curl gnupg && \
	curl -sL https://deb.nodesource.com/setup_11.x  | bash - && \
	apt-get -y install nodejs && \
	npm install && \
	apt-get -y upgrade && \
	apt-get install -y ffmpeg

WORKDIR /app
#ENV FLASK_APP=app.py
#ENV FLASK_DEBUG=1
RUN npm install fluent-ffmpeg && \
	pip install kafka-python

#CMD ["python", "-m", "flask", "run", "--host", "0.0.0.0"]
CMD ["python", "app.py"]
